[package]
name = "cyber_clara"
version = "0.1.0"
authors = ["Elias Floreteng <eliasfl@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
